import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[font]
size = 12
# normal      = { family = "JetBrainsMonoNL Nerd Font Mono", style = "Regular" }
# bold        = { family = "JetBrainsMonoNL Nerd Font Mono", style = "Bold" }
# italic      = { family = "JetBrainsMonoNL Nerd Font Mono", style = "Italic" }
# bold_italic = { family = "JetBrainsMonoNL Nerd Font Mono", style = "Bold Italic" }
normal      = { family = "MesloLGM Nerd Font", style = "Regular" }
bold        = { family = "MesloLGM Nerd Font", style = "Bold" }
italic      = { family = "MesloLGM Nerd Font", style = "Italic" }
bold_italic = { family = "MesloLGM Nerd Font", style = "Bold Italic" }

[shell]
program = "login"
args = ["-fp", "davidrosa"]

[[hints.enabled]]
command = "open"
hyperlinks = true
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[[keyboard.bindings]]
chars = "\u001BF"
key = "Right"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001BB"
key = "Left"
mods = "Alt"

[window]
# startup_mode = "Fullscreen"
dimensions = { columns = 200, lines = 25 }
padding = { x = 2, y = 2 }
blur = true
option_as_alt = "Both"

[mouse]
hide_when_typing = true

[env]
  TERM = "xterm-256color"
